# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client -y

    - name: Execute Shell Script on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.INPUT_PASSWORD }}
        script: |
        
          https://github.com/mzoughiwael/test3/blob/main/setup_dolibarr.sh.txt
