name: Install Apache on Azure VM
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Apache
        run: |
          az vm run-command invoke \
            --resource-group waelaz900 \
            --name waelTestVm \
            --command-id RunShellScript \
            --scripts "sudo apt-get update && sudo apt-get install -y apache2"
