name: Install Apache on Azure VM
on:
  push:
    branches:
      - main
  workflow_dispatch:




jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
       
      - name: Install Azure CLI
        run: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              az --version
               
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Apache
        run: |
          az vm run-command invoke \
            --resource-group waelaz900 \
            --name waelTestVm \
            --command-id RunShellScript \
            --scripts "sudo apt-get update && sudo apt-get install -y apache2"
      - name: Install Dolibarr
        run: |
          az vm run-command invoke \
            --resource-group waelaz900 \
            --name waelTestVm \
            --command-id RunShellScript \
            --scripts "sudo apt-get install -y php libapache2-mod-php php-mysql php-curl php-gd php-intl php-ldap php-mbstring php-xml php-zip && sudo wget https://download.dolibarr.org/download/stable/$(wget -qO- https://download.dolibarr.org/latest-stable.txt) -O dolibarr.zip && sudo unzip dolibarr.zip -d /var/www/html/ && sudo chown -R www-data:www-data /var/www/html/dolibarr/"
