# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - main




jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client -y
 
    - name: Update System Packages
      uses: actions/setup-python@v2
      with:
       python-version: '3.x'
      if: runner.os == 'Linux'
   
   
    - name: Install sshpass
      run: |
       apt-get update
       apt-get install -y sshpass
      if: runner.os == 'Linux' 
   
    - name: Update System Packages
      uses: appleboy/privileged-docker-action@master
      with:
       image: ubuntu
       entrypoint: bash
       script: |
          apt-get update
      if: runner.os == 'Linux'
    - name: Execute Shell Script on Azure VM
      uses: appleboy/ssh-action@master
      with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USERNAME }}
            password: ${{ secrets.INPUT_PASSWORD }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
        
                sshpass -p ${{ secrets.INPUT_PASSWORD }} ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} 
                 vim setup_dolibarr.sh
