name: Install Apache on Azure VM
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
       
      - name: Install Azure CLI
        run: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              az --version
               
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Dolibarr installation script
        run: |
          #!/bin/bash

          # Update and upgrade system packages
          apt update
          apt upgrade -y

          # Install Apache
          apt install apache2 -y

          # Start and enable Apache service
          systemctl start apache2
          systemctl enable apache2

          # Allow HTTP, HTTPS, and SSH through UFW
          ufw allow http
          ufw allow https
          ufw allow ssh
          ufw --force enable

          # Enable SSL module for Apache
          a2enmod ssl

          # Restart Apache
          systemctl restart apache2

          # Install PHP and required modules
          apt install php php-cli php-mysql php-common php-zip php-mbstring php-xmlrpc php-curl php-soap php-gd php-xml php-intl php-ldap libapache2-mod-php -y

          # Download Dolibarr
          wget https://www.dolibarr.org/files/stable/14.0.3/dolibarr-14.0.3.tgz

          # Extract Dolibarr archive
          tar xzf dolibarr-14.0.3.tgz

          # Move Dolibarr files to web directory
          mv dolibarr-14.0.3 /var/www/html/dolibarr

          # Set permissions
          chown -R www-data:www-data /var/www/html/dolibarr
          chmod -R 755 /var/www/html/dolibarr/documents/

          # Create Dolibarr database
          mysql -u root -p -e "CREATE DATABASE test;"
          mysql -u root -p -e "GRANT ALL PRIVILEGES ON test.* TO 'wael'@'localhost' IDENTIFIED BY 'Mzoughi@2023';"
          mysql -u root -p -e "FLUSH PRIVILEGES;"

          # Restart Apache
          systemctl restart apache2
